### PR TITLE
feat: adds support for npm lockfile v3

### PR DESCRIPTION
**Pull request by niklasheld**

### CODE REVIEW

**Comment by niklasheld** [comment]
Hello @Ginxo,
would you be able to take a look at this and potentially release a new version of this package?
The current version is broken with lock-files generated by recent NPM versions.
Thanks!

**Comment by Ginxo** [comment]
thanks for opening this @niklasheld I will take a look most probably this week, I keep you in touch

**Review by Ginxo — APPROVED** [review]
LGTM

**Review by lampajr — APPROVED** [review]

**Review by shubhbapna — APPROVED** [review]

**Comment by Ginxo** [comment]
many thanks for your contribution @niklasheld

**Pull request merged**
